ArbitrumFoundation/governance

- src-ts/proposalCreator.ts
- fixes https://github.com/ArbitrumFoundation/governance/issues/38
- refactor create / createTimelockScheduleArgs to use shared method
- default arg cleanup
> Proposal creator methods refactors / tweaks

- src/security-council-mgmt/governors/SecurityCouncilNomineeElectionGovernor.sol
possibly address this comment: https://github.com/ArbitrumFoundation/governance/pull/57#discussion_r1245008352
> nominee governor allow excluding current council members during random selection

- src/security-council-mgmt/governors/SecurityCouncilMemberElectionGovernor.sol
- src/security-council-mgmt/governors/modules/SecurityCouncilMemberElectionGovernorCountingUpgradeable.sol
* remove numerator and denominator in favor of just `fullWeightDuration`
* misc minor things
> SecurityCouncilMemberElectionGovernorCountingUpgradeable.votesToWeight refactor

- src/security-council-mgmt/SecurityCouncilManager.sol
- src/security-council-mgmt/governors/SecurityCouncilNomineeElectionGovernor.sol
- src/security-council-mgmt/interfaces/ISecurityCouncilManager.sol
renamed `firstCohort returns bool` to `firstCohortIncludes returns bool`
> implement *cohortIncludes on manager

- src/UpgradeExecRouterBuilder.sol
- src/security-council-mgmt/SecurityCouncilManager.sol
- src/security-council-mgmt/SecurityCouncilMgmtUtils.sol
- src/security-council-mgmt/interfaces/ISecurityCouncilManager.sol
* new `manager.getBothCohorts` public fn
* rename data to datas
* remove `removeSharedAddresses` from utils
> misc manager / routerbuilder / utils changes

- src/security-council-mgmt/Common.sol
- src/security-council-mgmt/SecurityCouncilManager.sol
- src/security-council-mgmt/errors.sol
- src/security-council-mgmt/interfaces/ISecurityCouncilManager.sol
- test/secuirty-council-mgmt/SecurityCouncilManager.t.sol
started to make it a library, but that ended up being very verbose
> Common.sol

- src/Util.sol
- src/security-council-mgmt/governors/SecurityCouncilMemberRemovalGovernor.sol
not sure if `Util.sol` is the best place for these new functions
> Util: getSelector and removeSelector

- src/security-council-mgmt/governors/SecurityCouncilMemberElectionGovernor.sol
- src/security-council-mgmt/governors/SecurityCouncilNomineeElectionGovernor.sol
- src/security-council-mgmt/governors/modules/ArbitrumGovernorProposalExpirationUpgradeable.sol
- test/security-council-mgmt/governors/SecurityCouncilMemberElectionGovernor.t.sol
- test/security-council-mgmt/governors/SecurityCouncilNomineeElectionGovernor.t.sol
override `state` to make proposals on both governors expire after 2 weeks. 
will write tests on this pr if we want to include this feature
> Security council governors: proposal expiration

- foundry.toml
- hardhat.config.ts
merge this, force push #123 back to [be81a84](https://github.com/ArbitrumFoundation/governance/pull/123/commits/be81a84bcaeecf319e63cbd887f222f292b524b1), merge base into #123
> Security council mgmt  optimizer profiles

- src/UpgradeExecRouteBuilder.sol
- src/security-council-mgmt/Common.sol
- src/security-council-mgmt/SecurityCouncilManager.sol
- src/security-council-mgmt/SecurityCouncilMemberSyncAction.sol
- src/security-council-mgmt/factories/L2SecurityCouncilMgmtFactory.sol
- src/security-council-mgmt/governors/SecurityCouncilMemberElectionGovernor.sol
- src/security-council-mgmt/governors/SecurityCouncilMemberRemovalGovernor.sol
- src/security-council-mgmt/governors/SecurityCouncilNomineeElectionGovernor.sol
- src/security-council-mgmt/governors/modules/ArbitrumGovernorVotesQuorumFractionUpgradeable.sol
- src/security-council-mgmt/governors/modules/SecurityCouncilMemberElectionGovernorCountingUpgradeable.sol
- src/security-council-mgmt/governors/modules/SecurityCouncilNomineeElectionGovernorCountingUpgradeable.sol
- src/security-council-mgmt/governors/modules/SecurityCouncilNomineeElectionGovernorTiming.sol
- src/security-council-mgmt/interfaces/ISecurityCouncilManager.sol
- src/security-council-mgmt/interfaces/ISecurityCouncilUpgradeExectutor.sol
updating comments, also deleted an unused interface
> Security council mgmt  comments

- scripts/security-council-mgmt-deployment/deployContracts.ts
> Additional Manager checks

- src/security-council-mgmt/governors/modules/SecurityCouncilMemberElectionGovernorCountingUpgradeable.sol
Added comment advising not to do this
> Full weight duration setting - C4 52

- hardhat.config.ts
- package.json
- scripts/security-council-mgmt-deployment/deployContracts.ts
- yarn.lock
* deploy gnosis safes with modules
* fixed nonce too low error because `.wait()` wasn't being awaited
* changed optimizer runs in hardhat config
> deploy gnosis safes properly and change hardhat config

- docs/gotchas.md
fixes https://github.com/ArbitrumFoundation/governance/issues/210
> update "gotchas" docs page: AIP 6 & 7 -related info, other cleanup / tweaks

- docs/gotchas.md
Gov: 0x5613AF0474EB9c528A34701A5b1662E3C8FA0678
Arb1: 0x554723262467F125Ac9e1cDFa9Ce15cc53822dbD
Nova: 0x71D78dC7cCC0e037e12de1E50f5470903ce37148
> docs: update gotchas.md

- src-ts/proposalStage.ts
alternative to https://github.com/ArbitrumFoundation/governance/pull/267
> get non-emergency action l2 timelock salt directly from calldata

- src/gov-action-contracts/AIPs/AIPArbOS30/ArbOneAIPArbOS30AddWasmCacheManagerAction.sol
- src/gov-action-contracts/AIPs/AIPArbOS30/ArbOneAIPArbOS30UpgradeChallengeManagerAction.sol
- src/gov-action-contracts/AIPs/AIPArbOS30/NovaAIPArbOS30AddWasmCacheManagerAction.sol
- src/gov-action-contracts/AIPs/AIPArbOS30/NovaAIPArbOS30UpgradeChallengeManagerAction.sol
- src/gov-action-contracts/AIPs/AIPArbOS30/SetArbOS30VersionAction.sol
- src/gov-action-contracts/AIPs/AIPArbOS30/parent_contracts/AIPArbOS30AddWasmCacheManagerAction.sol
- src/gov-action-contracts/AIPs/AIPArbOS30/parent_contracts/AIPArbOS30UpgradeChallengeManagerAction.sol
> stylus upgrade actions

- src/gov-action-contracts/AIPs/AIPNovaFeeRoutingAction.sol
Nova router: 0x36D0170D92F66e8949eB276C3AC4FEA64f83704d
L1 router: 0x40Cd7D713D7ae463f95cE5d342Ea6E7F5cF7C999
Action: 0x849E360a247132F961c9CBE95Ba39106c72e1268
> Redeploy routing action

- src/gov-action-contracts/AIPs/AIPArbOS31/SetArbOS31VersionAction.sol
- src/gov-action-contracts/arbos-upgrade/UpgradeArbOSVersionAtTimestampAction.sol
deployments, remember to update description of #296 after merging
```
SetArbOS31VersionAction: 0xaF81C82Ec98f86D0017d78cD66F1026f1A5Cf1Db @ 42161
SetArbOS31VersionAction: 0x6dD43360d2a69BB9FfFC5349F2511f2A3bCbC2da @ 42170
```
> Arbos 31 timed upgrade action

- src/security-council-mgmt/governors/SecurityCouncilNomineeElectionGovernor.sol
- src/security-council-mgmt/governors/modules/SecurityCouncilNomineeElectionGovernorTiming.sol
- Change comments reflecting the new `cadenceInMonths` behavior
- Change nextElectionDate by nextElectionYear for clarity
> Simple cadence minor fixes
